### User sign up endpoint

POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Shahnawaz",
    "company": "odoo",
    "address": "San Jose",
    "phone": "6693198451",
    "email": "shan3@odoo.com",
    "password": "secret123"
}

### User login up endpoint

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "shan3@odoo.com",
    "password": "secret123" 
}